{% set name = "hspf_utils" %}
{% set version = "6.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hspf_utils-{{ version }}.tar.gz
  sha256: 116040df9554de20595902892802fb8c58db903843c18774a9d936aad9b943b1

build:
  entry_points:
    - hspf_utils = hspf_utils.hspf_utils:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas
    - toolbox_utils >=3.0.0,<4.0.0
    - cltoolbox >1.1.0
    - hspfbintoolbox >=9.0.0,<10.0.0

test:
  imports:
    - hspf_utils
  commands:
    - pip check
    - hspf_utils --help
  requires:
    - pip

about:
  summary: Command line script and Python library to develop water balance from HSPF models
  home: https://pypi.org/project/hspf-utils/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
